version: '3.8'

services:
  web:
    build: ./recipeproject
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - ./recipeproject/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=recipeadmin
      - POSTGRES_PASSWORD=D1ck123!
      - POSTGRES_DB=recipeblog

volumes:
  postgres_data:
